#puerto 
server:
  port: 8090
#lee del cliente student-service 
zuul:
   prefix: /app
   routes:
      student:
#         url: http://localhost:8090
         path: /persona-api/**
         service-id: PERSONA-SERVICE
   
      clientenodejs:
         url: http://localhost:5000
         
         

#para habilitar Ribbon
ribbon:
   eureka:
      enabled: true
#registro con eureka
eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}