version: "3"


services:
  ceropapel-getdocpublicado:
    command: [ "npm", "start" ]
    build: . 
    image: ceropapel/get-doc-publicado:obtiene-doc-publicado
    container_name: ceropapel-getdocpublicado
    network_mode: bridge
    ports:
      - "5005:5005"
    volumes: 
      - .:/opt/app
      - /opt/app/node_modules



      
      
